# Generated by Django 2.2.6 on 2019-10-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('number', models.IntegerField()),
                ('exist', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
