# Generated by Django 2.2.6 on 2019-10-17 21:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(default='ABS', max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AbsMethodExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('named', models.CharField(default='Name AbsMethod class', max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AbsSum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namex', models.CharField(default='XXX', max_length=10)),
                ('namey', models.CharField(default='YYY', max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookExample',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('detail_text', models.TextField()),
                ('detail_json', django.contrib.postgres.fields.jsonb.JSONField(default=None)),
            ],
            options={
                'verbose_name': 'Book Example',
                'verbose_name_plural': 'Book Examples',
                'db_table': 'book_example',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FirstModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='MainFirstModel', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MixOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abs', models.CharField(default='abstract', max_length=10)),
                ('name', models.CharField(default='MixOne', max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OneExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('number', models.IntegerField()),
                ('exist', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SecondModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('named', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_model.FirstModel')),
            ],
        ),
        migrations.CreateModel(
            name='MixTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('named', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_model.MixOne')),
            ],
        ),
    ]
