# Generated by Django 2.2.6 on 2019-10-22 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Screens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_screen', models.CharField(max_length=50)),
                ('seats', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_model.MovieHouse')),
            ],
        ),
    ]
