# Generated by Django 2.2.6 on 2019-10-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(default='ABS', max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
