# Generated by Django 2.2.6 on 2019-10-08 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_model', '0002_absexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='MainFirstModel', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SecondModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('named', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_model.FirstModel')),
            ],
        ),
    ]
