# Generated by Django 2.2.6 on 2019-10-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_model', '0002_moviehouse_screens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviehouse',
            name='cinema_name',
            field=models.CharField(max_length=50),
        ),
    ]
