# Generated by Django 2.2.6 on 2019-10-09 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_model', '0003_firstmodel_secondmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MixOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abs', models.CharField(default='abstract', max_length=10)),
                ('name', models.CharField(default='MixOne', max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MixTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('named', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_model.MixOne')),
            ],
        ),
    ]
