# Generated by Django 2.2.6 on 2019-10-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_model', '0004_mixone_mixtwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsSum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namex', models.CharField(default='XXX', max_length=10)),
                ('namey', models.CharField(default='YYY', max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
